CREATE SCHEMA IF NOT EXISTS flashmind;

CREATE TABLE IF NOT EXISTS flashmind.users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flashmind.decks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES flashmind.users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flashmind.cards (
  id SERIAL PRIMARY KEY,
  deck_id INTEGER REFERENCES flashmind.decks(id) ON DELETE CASCADE,
  front TEXT NOT NULL,
  back TEXT NOT NULL,
  media_type VARCHAR(50) DEFAULT 'text',
  media_url TEXT,
  state VARCHAR(50) DEFAULT 'NOVO', -- NOVO, APRENDENDO, REVISÃO
  learning_step_index INTEGER DEFAULT 0,
  interval_days REAL DEFAULT 0,
  ease_factor REAL DEFAULT 2.5,
  repetitions INTEGER DEFAULT 0,
  next_review_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
